# Generated by Django 2.1.7 on 2019-05-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=20)),
                ('ocount', models.IntegerField()),
                ('oamount', models.IntegerField()),
                ('shopid', models.IntegerField()),
            ],
            options={
                'db_table': 'order_db',
            },
        ),
    ]
