# Generated by Django 2.1.7 on 2019-05-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oamount',
            new_name='oammount',
        ),
        migrations.AddField(
            model_name='order',
            name='liuyan',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='o_img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='已支付', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
