# Generated by Django 2.1.7 on 2019-05-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190516_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shopid',
            new_name='oshopid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='liuyan',
        ),
        migrations.AddField(
            model_name='order',
            name='oprice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='orderid',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
