# Generated by Django 2.1.7 on 2019-05-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190517_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='oshopid',
        ),
        migrations.AddField(
            model_name='order',
            name='oshopname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default='未完成', max_length=10),
        ),
    ]
