# Generated by Django 2.1.7 on 2019-05-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190517_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oprice',
            field=models.CharField(max_length=30),
        ),
    ]
