# Generated by Django 2.1.7 on 2019-05-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190517_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oammount',
            field=models.CharField(max_length=40),
        ),
    ]
