# Generated by Django 2.1.7 on 2019-05-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190517_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '订单管理'},
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[(0, '未完成'), (1, '已完成')], default='0', max_length=10, verbose_name='订单状态'),
        ),
    ]
