# Generated by Django 2.1.7 on 2019-05-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190521_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default='未完成', max_length=10),
        ),
    ]
