# Generated by Django 2.1.7 on 2019-05-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20190530_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('未完成', '未完成'), ('已完成', '已完成')], default='未完成', max_length=10, verbose_name='订单状态'),
        ),
    ]
