# Generated by Django 2.1.7 on 2019-05-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=15, verbose_name='用户名')),
                ('aphone', models.CharField(max_length=20, verbose_name='电话')),
                ('asheng', models.CharField(max_length=30, verbose_name='省份/自治区')),
                ('acity', models.CharField(max_length=50, verbose_name='城市/地区')),
                ('aqu', models.CharField(max_length=40, verbose_name='区/县')),
                ('amenpai', models.CharField(max_length=50, verbose_name='街道地址，门牌')),
                ('abq', models.CharField(max_length=20, verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '地址管理',
                'db_table': 'address_user',
            },
        ),
    ]
