# Generated by Django 2.1.7 on 2019-04-22 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20190410_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'db_table': 'shopping_db',
            },
        ),
    ]
