# Generated by Django 2.1.7 on 2019-07-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_goods_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='sid',
            field=models.IntegerField(),
        ),
    ]
