# Generated by Django 2.1.7 on 2019-04-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='login_user',
        ),
    ]
