# Generated by Django 2.1.7 on 2019-07-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190504_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户管理'},
        ),
    ]
