# Generated by Django 2.1.7 on 2019-04-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20190409_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_daily',
            name='fname',
            field=models.CharField(max_length=30, verbose_name='菜名'),
        ),
        migrations.AlterField(
            model_name='food_daily',
            name='ftype',
            field=models.CharField(choices=[('food_tj', '推荐菜品'), ('food_ts', '本店特色'), ('food_rc', '热菜'), ('food_lc', '凉菜'), ('food_tg', '汤羹'), ('food_zs', '主食'), ('food_xc', '小吃'), ('food_js', '饮品酒水')], max_length=30, verbose_name='菜系'),
        ),
        migrations.AlterField(
            model_name='food_daily',
            name='gimg',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='food_daily',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格'),
        ),
    ]
