# Generated by Django 2.1.7 on 2019-05-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20190415_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food_daily',
            options={'verbose_name_plural': '菜单表'},
        ),
        migrations.AlterModelTable(
            name='food_daily',
            table='food_food_daily',
        ),
    ]
