# Generated by Django 2.1.7 on 2019-05-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20190504_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_daily',
            name='ftype',
            field=models.CharField(choices=[('food_rc', '热菜'), ('food_lc', '凉菜'), ('food_tg', '汤羹'), ('food_zs', '主食'), ('food_xc', '小吃'), ('food_js', '饮品酒水'), ('food_hx', '海鲜')], max_length=30, verbose_name='菜系'),
        ),
    ]
