# Generated by Django 2.1.7 on 2019-07-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20190508_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food_daily',
            options={'verbose_name_plural': '菜单管理'},
        ),
        migrations.AlterField(
            model_name='food_daily',
            name='gimg',
            field=models.ImageField(upload_to='static/images', verbose_name='上传图片'),
        ),
    ]
